// get a list of genres
export const FETCH_GENRES_LIST_START = 'FETCH_GENRES_LIST_START'
export const FETCH_GENRES_LIST_SUCCESS = 'FETCH_GENRES_LIST_SUCCESS'
export const FETCH_GENRES_LIST_FAILURE = 'FETCH_GENRES_LIST_FAILURE'
