// get a list of movies
export const FETCH_MOVIES_LIST_START = 'FETCH_MOVIES_LIST_START'
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS'
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE'

export const CLEAR_MOVIES_LIST = 'CLEAR_MOVIES_LIST'
