// get a list of movies
export const FETCH_MOVIES_LIST_START = 'FETCH_MOVIES_LIST_START'
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS'
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE'

// get a list of recommended movies
export const FETCH_RECOMMENDED_MOVIES_LIST_START = 'FETCH_RECOMMENDED_MOVIES_LIST_START'
export const FETCH_RECOMMENDED_MOVIES_LIST_SUCCESS = 'FETCH_RECOMMENDED_MOVIES_LIST_SUCCESS'
export const FETCH_RECOMMENDED_MOVIES_LIST_FAILURE = 'FETCH_RECOMMENDED_MOVIES_LIST_FAILURE'

// get a details of the movie
export const FETCH_MOVIE_DETAILS_START = 'FETCH_MOVIE_DETAILS_START'
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS'
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE'

export const CLEAR_MOVIES_LIST = 'CLEAR_MOVIES_LIST'
